id: P41F4B7B2
initial_creation_type: input
source_metadata:
  title: Saṅghabhedavastu
  language: zh
  volumes:
    9eea743861914f9286d9b2a9fe3e3e15:
      title: Title
      base_file: Title.txt
      work_id: W0FE94419
  chapter_to_tile: {}
created_at: '2022-03-01T22:59:37.060692'
last_modified_at: '2022-03-01T22:59:37.060701'
